FLAGS=-O3 -Wall -lm

all: walk walk_loop walk_loop2

walk: walk.c
	gcc walk.c -o walk $(FLAGS)

walk_loop: walk_loop.c
	gcc walk_loop.c -o walk_loop $(FLAGS)

walk_loop2: walk_loop2.c
	gcc walk_loop2.c -o walk_loop2 $(FLAGS)